[package]
name = "pipe2"
version = "0.1.0"
edition = "2024"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.30.1", features = ["fs"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winnt", "namedpipeapi", "fileapi", "errhandlingapi", "winerror"] }
